# docker-compose.yml
# Use with podman-compose up and podman-compose down

version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:16
    container_name: abrolhos-postgres
    environment:
      POSTGRES_USER: abrolhos
      POSTGRES_PASSWORD: abrolhos
      POSTGRES_DB: abrolhos
    ports:
      - "5432:5432"
    volumes:
      - /home/anisio/IdeaProjects/abrolhos/container/local:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  abrolhos_pgdata: