package br.dev.demoraes.abrolhos.application.services

import br.dev.demoraes.abrolhos.domain.entities.TotpSecret
import dev.turingcomplete.kotlinonetimepassword.GoogleAuthenticator
import org.apache.commons.codec.binary.Base32
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.util.Date

/**
 * Oathtool Cross-Validation Test
 *
 * This test generates TOTP codes using kotlin-onetimepassword and documents
 * the expected oathtool command for manual verification. This allows us to
 * compare the library's output with the standard oathtool implementation.
 *
 * **Validates: Requirements 2.1, 2.4**
 *
 * To manually verify the codes generated by this test, use the oathtool command:
 * ```
 * oathtool --totp -b <BASE32_SECRET> --now=<UNIX_TIMESTAMP>
 * ```
 *
 * Example:
 * ```
 * oathtool --totp -b JBSWY3DPEHPK3PXP --now=1234567890
 * ```
 */
class TotpOathtoolCrossValidationTest {
    private val totpService = TotpService()

    /**
     * Test secret for cross-validation
     * Using a well-known test secret for reproducibility
     */
    private val testSecret = "JBSWY3DPEHPK3PXP"

    /**
     * Test timestamps for cross-validation
     * Using fixed timestamps for reproducible results
     */
    private val testTimestamps = listOf(
        1234567890L, // 2009-02-13 23:31:30 UTC
        1111111109L, // 2005-03-18 01:58:29 UTC
        1111111111L, // 2005-03-18 01:58:31 UTC
        1234567800L, // 2009-02-13 23:30:00 UTC
        1700000000L // 2023-11-14 22:13:20 UTC
    )

    @Test
    fun `should generate codes and document oathtool commands for verification`() {
        // Given: A test secret
        val secret = TotpSecret(testSecret)
        val base32 = Base32()
        val secretBytes = base32.decode(secret.value.uppercase())
        val generator = GoogleAuthenticator(secretBytes)

        // When/Then: Generate codes and document oathtool commands
        println("\n=== Oathtool Cross-Validation Test ===")
        println("Secret: $testSecret")
        println("Library: kotlin-onetimepassword (GoogleAuthenticator)")
        println()
        println("To verify these codes with oathtool, run the following commands:")
        println()

        testTimestamps.forEach { timestamp ->
            val date = Date(timestamp * 1000)
            val code = generator.generate(date)

            println("# Timestamp: $timestamp ($date)")
            println("oathtool --totp -b $testSecret --now=$timestamp")
            println("kotlin-onetimepassword generated: $code")
            println()

            // Verify code format
            assertEquals(6, code.length, "Code should be 6 digits")
            assertTrue(code.all { it.isDigit() }, "Code should be numeric")
        }

        println("=== Manual Verification Instructions ===")
        println("1. Install oathtool: sudo apt-get install oathtool (Ubuntu/Debian)")
        println("2. Run each command above and compare the output with the generated code")
        println("3. The codes should match if the library is RFC 6238 compliant")
        println("4. If codes don't match, there may be a library implementation issue")
        println("=====================================\n")
    }

    @Test
    fun `should generate codes at same timestamp using TotpService`() {
        // Given: A test secret and fixed timestamp
        val secret = TotpSecret(testSecret)
        val timestamp = Date(1234567890L * 1000)

        // When: Generate codes using TotpService
        val windowCodes = totpService.generateCodesForWindows(secret, timestamp)

        // Then: Document the codes for manual verification
        println("\n=== TotpService Cross-Validation ===")
        println("Secret: $testSecret")
        println("Timestamp: 1234567890 ($timestamp)")
        println()
        println("Previous window (-30s): ${windowCodes.previous}")
        println("Current window:         ${windowCodes.current}")
        println("Next window (+30s):     ${windowCodes.next}")
        println()
        println("To verify with oathtool:")
        println("oathtool --totp -b $testSecret --now=1234567860  # Previous")
        println("oathtool --totp -b $testSecret --now=1234567890  # Current")
        println("oathtool --totp -b $testSecret --now=1234567920  # Next")
        println("=====================================\n")

        // Verify code format
        assertEquals(6, windowCodes.previous.length)
        assertEquals(6, windowCodes.current.length)
        assertEquals(6, windowCodes.next.length)
    }

    @Test
    fun `should generate consistent codes for same timestamp`() {
        // Given: A test secret and fixed timestamp
        val secret = TotpSecret(testSecret)
        val timestamp = Date(1234567890L * 1000)
        val base32 = Base32()
        val secretBytes = base32.decode(secret.value.uppercase())
        val generator = GoogleAuthenticator(secretBytes)

        // When: Generate code multiple times
        val code1 = generator.generate(timestamp)
        val code2 = generator.generate(timestamp)

        // Then: Codes should be identical
        assertEquals(code1, code2, "Same timestamp should produce same code")
    }

    @Test
    fun `should generate codes for production secret and document verification`() {
        // Given: The production secret from the bug report
        val productionSecret = TotpSecret("KNT7MHTHYMB2HQR7RG7MQBD6GPQLOJ2T")
        val timestamp = Date(1700000000L * 1000)

        // When: Generate codes using TotpService
        val windowCodes = totpService.generateCodesForWindows(productionSecret, timestamp)

        // Then: Document the codes for manual verification
        println("\n=== Production Secret Cross-Validation ===")
        println("Secret: KNT7MHTHYMB2HQR7RG7MQBD6GPQLOJ2T")
        println("Timestamp: 1700000000 ($timestamp)")
        println()
        println("Previous window (-30s): ${windowCodes.previous}")
        println("Current window:         ${windowCodes.current}")
        println("Next window (+30s):     ${windowCodes.next}")
        println()
        println("To verify with oathtool:")
        println("oathtool --totp -b KNT7MHTHYMB2HQR7RG7MQBD6GPQLOJ2T --now=1699999970  # Previous")
        println("oathtool --totp -b KNT7MHTHYMB2HQR7RG7MQBD6GPQLOJ2T --now=1700000000  # Current")
        println("oathtool --totp -b KNT7MHTHYMB2HQR7RG7MQBD6GPQLOJ2T --now=1700000030  # Next")
        println()
        println("To verify with Google Authenticator or Authy:")
        println("1. Add the secret to your authenticator app")
        println("2. Compare the displayed code with the 'Current window' code above")
        println("3. The codes should match within the 30-second window")
        println("==========================================\n")

        // Verify code format
        assertEquals(6, windowCodes.previous.length)
        assertEquals(6, windowCodes.current.length)
        assertEquals(6, windowCodes.next.length)
    }

    @Test
    fun `should validate that codes change across time windows`() {
        // Given: A test secret
        val secret = TotpSecret(testSecret)
        val base32 = Base32()
        val secretBytes = base32.decode(secret.value.uppercase())
        val generator = GoogleAuthenticator(secretBytes)

        // When: Generate codes for different time windows
        val timestamp1 = Date(1234567890L * 1000)
        val timestamp2 = Date((1234567890L + 30) * 1000) // 30 seconds later
        val timestamp3 = Date((1234567890L + 60) * 1000) // 60 seconds later

        val code1 = generator.generate(timestamp1)
        val code2 = generator.generate(timestamp2)
        val code3 = generator.generate(timestamp3)

        // Then: Codes should typically be different across windows
        // (though theoretically they could be the same by chance)
        println("\n=== Time Window Validation ===")
        println("Code at T+0s:  $code1")
        println("Code at T+30s: $code2")
        println("Code at T+60s: $code3")
        println("==============================\n")

        // Verify all codes are valid format
        assertEquals(6, code1.length)
        assertEquals(6, code2.length)
        assertEquals(6, code3.length)
    }
}
